### ISSUE TITLE
Not working with new transip API

### ISSUE THREAD

**Issue by vascotenner** [Jerrythafast/transip-dyndns#1]
This code is not working with the modern transip API as can be found here:
https://github.com/transip/transip-api-php

This repositories works: https://github.com/thijsbrilleman/dynamic-ip-transip-automatic-update

**Comment by Jerrythafast** [comment]
Ah, I completely forgot about this repo! I have replaced the old PHP script with a Python script that I've been using since a (long) while. It is almost a drop-in replacement for the old PHP script. Functional differences with the script linked above are:
1. My script can update multiple DNS entries for different domains.
2. My script will keep in sync all DNS entries that have the same IP address (you only need to specify one though, it will find the others by itself).
3. My script accepts the IPv6 address to use as a command-line argument.

If you don't need all of that, the script linked above is equivalent.

**Comment by vascotenner** [comment]
Thank you for the update.
